export const AUDIT_ACTION_LABELS: Record<string, string> = {
  invoice_created: "Invoice created",
  invoice_sent: "Sent to customer",
  invoice_resent: "Reminder sent to customer",
  invoice_marked_paid: "Marked as paid",
  invoice_cancelled: "Cancelled",
  payment_reference_submitted: "Payment reference submitted",
  shipment_status_updated: "Shipment status updated",
  driver_assigned: "Driver assigned",
  assignment_completed: "Assignment completed",
  claim_filed: "Claim filed",
  claim_status_updated: "Claim status updated",
  quote_status_updated: "Quote status updated",
  lead_status_updated: "Status updated",
  lead_assigned: "Lead assigned",
  lead_note_added: "Note added",
  lead_contact_logged: "Contact logged",
  lead_category_updated: "Category updated",
  lead_updated: "Lead details updated",
  payment_proof_uploaded: "Payment proof uploaded",
  "organization.settings_updated": "Platform settings updated",
};
